apiVersion: batch/v1
kind: Job
metadata:
  name: worker
spec:
  parallelism: 6
  template:
    metadata:
      name: worker
    spec:
      containers:
      - name: worker
        image: bioconductor/bioc-redis-worker:bioconductor-docker-devel
        imagePullPolicy: Always
        resources:
          requests:
            memory: 3Gi
            cpu: 2
          limits:
            memory: 4Gi
            cpu: 3
        volumeMounts:
        - mountPath: /host
          name: test-nfs-mount
        command: ["R"]
        args: ["-f", "/home/docker/worker.R"]
      restartPolicy: OnFailure
      volumes:
      - name: test-nfs-mount
        persistentVolumeClaim:
          claimName: nfs
